# Generated by Django 5.2.6 on 2026-07-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_gateway',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('RAZORPAY', 'Razorpay')], max_length=15),
        ),
    ]
