# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0003_badge_course_category_user_level_user_xp_project_and_more')]

    operations = [
        migrations.AddField(
            model_name='qamessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_qa_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
